CREATE TABLE PACKS
(
  ID BIGSERIAL NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PACK_HISTORY
(
  ID BIGSERIAL NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  SUBS_ID BIGINT NOT NULL,
  PACK_ID BIGINT NOT NULL,
  ACTION INTEGER NOT NULL,
  TRACE_NUMBER BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT
(
  ID BIGSERIAL NOT NULL,
  START TIMESTAMP NOT NULL,
  "END" TIMESTAMP NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_RELS
(
  PARENT_ID BIGINT NOT NULL,
  RELS_TO BIGINT NOT NULL,
  RELS_TYPE INTEGER NOT NULL,
  PRIMARY KEY (PARENT_ID, RELS_TO)
);

CREATE TABLE MAPPER
(
  PACK_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  PRIMARY KEY (PACK_ID, PRODUCT_ID)
);

ALTER TABLE PACKS ADD CONSTRAINT UK_PACKS_NAME UNIQUE (NAME);
ALTER TABLE PRODUCT ADD CONSTRAINT UK_PRODUCT_NAME UNIQUE (NAME);
ALTER TABLE PACK_HISTORY ADD CONSTRAINT UK_PACK_HISTORY UNIQUE (PACK_ID, TRACE_NUMBER);

ALTER TABLE PACK_HISTORY ADD CONSTRAINT FK_PACK_HISTORY_TO_PACKS FOREIGN KEY (PACK_ID) REFERENCES PACKS (ID);
ALTER TABLE PRODUCT_RELS ADD CONSTRAINT FK_PRODUCT_RELS_TO_PARENT_PRODUCT FOREIGN KEY (PARENT_ID) REFERENCES PRODUCT (ID);
ALTER TABLE PRODUCT_RELS ADD CONSTRAINT FK_PRODUCT_RELS_TO_PRODUCT FOREIGN KEY (RELS_TO) REFERENCES PRODUCT (ID);
ALTER TABLE MAPPER ADD CONSTRAINT FK_MAPPER_TO_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);
ALTER TABLE MAPPER ADD CONSTRAINT FK_MAPPER_TO_PACKS FOREIGN KEY (PACK_ID) REFERENCES PACKS (ID);